application: your-project-id
version: 1
runtime: go
api_version: go1
# 靜態資源的快取設定
default_expiration: "1d"
handlers:
- url: /go/.*
  script: _go_app
- url: /(.+)
  static_files: web/\1
  upload: web/(.+)
- url: /
  static_files: web/index.html
  upload: web/index.html

