application: your-project-id
version: 1
runtime: go
api_version: go1
# 靜態資源的快取設定
default_expiration: "1d"
handlers:
- url: /go/.*
  script: _go_app
# 必須將/_ah/打開，不然收得到channel事件的request但是無法處理
- url: /_ah/.*
  script: _go_app
- url: /(.+)
  static_files: web/\1
  upload: web/(.+)
- url: /
  static_files: web/index.html
  upload: web/index.html
# 傾聽事件
# google 的 channel會自己在前台送request到
# /_ah/channel/connected 和 /_ah/channel/disconnected
# 前台會一直polling，所以這個功能最好使用在小型專案
inbound_services:
- channel_presence
